name: build-wheels

on:
  push:
    branches:
      - master
    tags:
      - '*'

concurrency:
  group: build-wheels-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        shell: bash
        run: |
          python3 -m pip install --upgrade build
          python3 -m build -s
          ls -l dist/*

      - name: Publish sdist to PyPI
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel twine==6.0.1 setuptools

          twine upload dist/simple_sentencepiece-*.tar.gz

      # see https://cibuildwheel.readthedocs.io/en/stable/changelog/
      # for a list of versions
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_SKIP: "cp27-* cp35-* cp36-* *-win32 pp* *-musllinux* *-manylinux_i686"
          CIBW_BUILD_VERBOSITY: 3

      - name: Display wheels
        shell: bash
        run: |
          ls -lh ./wheelhouse/

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel twine==6.0.1 setuptools

          twine upload ./wheelhouse/*.whl
